

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - restore_cache:
            name: Restore node_modules cache
            keys:
              - v1-node-{{ checksum "yarn.lock" }}
              - v1-node-

      - run: ls && cd work && ls

      - run:
            name: Install dependencies
            command: cd  ./work && yarn install


      - run:
            name: Run build script
            command: cd ./work && yarn build

      - run:
            name: Deploy to firebase
            command: cd ./work && ls && yarn firebase:prod

      - run: echo $FIRE

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Slash
          filters:
            branches:
              only: master
