

version: 2
jobs:
  slash_staging:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - restore_cache:
            name: Restore node_modules cache
            keys:
              - v1-node-{{ checksum "./trial/yarn.lock" }}
              - v1-node-

      - run:
            name: Install dependencies
            command: cd ./trial && yarn install

      - run:
            name: Run build script
            command: cd ./trial && yarn build

      - run:
            name: Deploy to firebase
            command: cd ./trial && yarn deploy:circle

      - save_cache:
            name: Save modules to cache
            key: v1-node-{{ checksum "./trial/yarn.lock" }}
            paths:
              - ./trial/node_modules

workflows:
  version: 2
  build-deploy:
    jobs:
      - slash_staging:
          context: Slash
          filters:
            branches:
              only: slash-staging

