

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - run:
            name: Change working directory
            command: |
              echo 'export CIRCLE_WORKING_DIRECTORY="~/project/trial"' >> $BASH_ENV
      - run:
            name: Testing working dir
            command: pwd

      - restore_cache:
            name: Restore node_modules cache
            keys:
              - v1-node-{{ checksum "./trial/yarn.lock" }}
              - v1-node-
      - run:
            name: Load variables from file
            command: |
              env
              set -a
              . ./trial/.env
              set +a
              env

      - run:
            name: Test availability
            command: |
              env
              echo $APP_DOMAIN

      - run:
            name: Install dependencies
            command: cd ./trial && yarn install

      - run:
            name: Run build script
            command: cd ./trial && yarn build

      - run:
            name: Deploy to firebase
            command: cd ./trial && yarn deploy:circle

      - save_cache:
            name: Save modules to cache
            key: v1-node-{{ checksum "./trial/yarn.lock" }}
            paths:
              - ./trial/node_modules

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Slash
          filters:
            branches:
              only: staging

