

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    steps:
      - checkout
      - restore_cache:
            name: Restore node_modules cache
            keys:
        - slash-{{ checksum "yarn.lock" }}
        - slash-

      - run:
            name: Install dependencies
            command: yarn install --modules-folder ./work

      - run:
            name: Run build script
            command: cd ./work && yarn build

      - run:
            name: Deploy to firebase
            command: cd ./work && yarn firebase:prod

      - run: echo $FIRE

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Slash
          filters:
            branches:
              only: master
